# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/devel/php56i-tokenizer/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php56i

PKGNAMESUFFIX=	-tokenizer

.include "${MASTERDIR}/Makefile"
