# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/graphics/php56i-exif/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	graphics

MASTERDIR=	${.CURDIR}/../../lang/php56i

PKGNAMESUFFIX=	-exif

.include "${MASTERDIR}/Makefile"
