# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/security/php56i-mcrypt/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php56i

PKGNAMESUFFIX=	-mcrypt

.include "${MASTERDIR}/Makefile"
