# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/devel/php56i-readline/Makefile 445214 2017-07-07 08:10:30Z ale $

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php56i

PKGNAMESUFFIX=	-readline

.include "${MASTERDIR}/Makefile"
