# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/www/php56i-opcache/Makefile 463917 2018-03-08 19:48:41Z mat $

CATEGORIES=	www

MASTERDIR=	${.CURDIR}/../../lang/php56i

PKGNAMESUFFIX=	-opcache

USES=	php:zend,noflavors

.include "${MASTERDIR}/Makefile"
