# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/sysutils/php56i-posix/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	sysutils

MASTERDIR=	${.CURDIR}/../../lang/php56i

PKGNAMESUFFIX=	-posix

.include "${MASTERDIR}/Makefile"
