# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/databases/php56i-sybase_ct/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php56i

PKGNAMESUFFIX=	-sybase_ct

.include "${MASTERDIR}/Makefile"
