# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/archivers/php56i-bz2/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	archivers

MASTERDIR=	${.CURDIR}/../../lang/php56i

PKGNAMESUFFIX=	-bz2

.include "${MASTERDIR}/Makefile"
