# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/misc/php56i-calendar/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	misc

MASTERDIR=	${.CURDIR}/../../lang/php56i

PKGNAMESUFFIX=	-calendar

.include "${MASTERDIR}/Makefile"
