# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/net/php56i-xmlrpc/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	net

MASTERDIR=	${.CURDIR}/../../lang/php56i

PKGNAMESUFFIX=	-xmlrpc

.include "${MASTERDIR}/Makefile"
