# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/net-mgmt/php56i-snmp/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	net-mgmt

MASTERDIR=	${.CURDIR}/../../lang/php56i

PKGNAMESUFFIX=	-snmp

.include "${MASTERDIR}/Makefile"
