# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/textproc/php56i-dom/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php56i

PKGNAMESUFFIX=	-dom

.include "${MASTERDIR}/Makefile"
