# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/security/php56i-filter/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php56i

PKGNAMESUFFIX=	-filter

.include "${MASTERDIR}/Makefile"
