# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/converters/php56i-recode/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	converters

MASTERDIR=	${.CURDIR}/../../lang/php56i

PKGNAMESUFFIX=	-recode

.include "${MASTERDIR}/Makefile"
