# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/graphics/php56i-gd/Makefile 466773 2018-04-08 06:59:57Z ale $

CATEGORIES=	graphics

MASTERDIR=	${.CURDIR}/../../lang/php56i

PKGNAMESUFFIX=	-gd

.include "${MASTERDIR}/Makefile"
